- hosts: all

  pre_tasks:
   - ansible.builtin.apt:
        update_cache: yes

  roles:
   - name: geerlingguy.pip
     tags:
        - python

  tasks:
   - name: Genarate .env file
     ansible.builtin.template:
        src: ./templates/.env.j2
        dest: ~/.env
     tags:
        - prepare

   - name: Start a container
     community.docker.docker_container:
        name: my-redmine
        image: redmine
        state: started
        ports:
         - "80:3000"
        env_file: ~/.env
     tags:
        - prepare


- hosts: all

  roles:
   - name: datadog.datadog
     tags:
        - deploy
