- hosts: all

  pre_tasks:
   - ansible.builtin.apt:
        update_cache: yes

  roles:
   - geerlingguy.pip

  tasks:
   - name: Genarate .env file
     ansible.builtin.template:
        src: ./templates/.env.j2
        dest: ~/.env


   - name: Start a container
     community.docker.docker_container:
        name: my-redmine
        image: redmine
        state: started
        ports:
         - "80:3000"
        env_file: ~/.env

   - name: Import the Datadog Agent role from the Datadog collection
     import_role:
        name: datadog.dd.agent
  vars:
    datadog_app_key: "f3bc332ebabe4bfb183fffcb96da35837a809c7c"
    datadog_api_key: "c1391f3d52853ec046e6478d5597df62"
    datadog_site: "datadoghq.eu"
    datadog_checks:
     http_check:
       init_config:

       instances:
         - name: Redmine
           url: http://localhost
