- hosts: all

  tasks:
   - name: Genarate .env file
     ansible.builtin.template:
#        src: ./.env
#        dest: ~/.env
        src: ./templates/.env.j2
        dest: ~/.env


   - name: Start a container
     community.docker.docker_container:
        name: my-redmine
        image: redmine
        state: started
        ports:
         - "80:3000"
        env_file: ~/.env
